# Tag-based Dispatcher
# Generated by generate_mobs.py

# マーカー(@s)のタグを見て、対応するRegister関数を呼び出す
execute if entity @s[tag=mob.001.goblin] run function bank:mob/001.goblin/register
execute if entity @s[tag=mob.002.skeleton_warrior] run function bank:mob/002.skeleton_warrior/register
execute if entity @s[tag=mob.003.dark_knight] run function bank:mob/003.dark_knight/register
execute if entity @s[tag=mob.004.test_man] run function bank:mob/004.test_man/register
execute if entity @s[tag=mob.005.test_woman] run function bank:mob/005.test_woman/register
execute if entity @s[tag=mob.006.test_master] run function bank:mob/006.test_master/register
execute if entity @s[tag=mob.007.test_summoner] run function bank:mob/007.test_summoner/main/register
execute if entity @s[tag=mob.main] run function bank:mob/007.test_summoner/main/register
execute if entity @s[tag=mob.008.henchman] run function bank:mob/007.test_summoner/008.henchman/register